name: Develop Branch Workflow

on:
    workflow_dispatch:

jobs:
    Build:
        uses: ./.github/workflows/build.yml
        secrets: inherit

    Upload:
        needs: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Install SSH key
                uses: webfactory/ssh-agent@v0.5.3
                with:
                    ssh-private-key: ${{ secrets.ASSETS_PRIVATE_KEY }}

            -   name: Download artifacts from build
                uses: actions/download-artifact@v2
                with:
                    path: dist

            -   name: Upload assets via SCP
                env:
                    HOST: ${{ secrets.ASSETS_HOST }}
                    PORT: ${{ secrets.ASSETS_PORT }}
                    USER: ${{ secrets.ASSETS_USER }}
                run: |
                    scp -P $PORT -o StrictHostKeyChecking=no -r dist/* $USER@$HOST:/files/
                shell: bash
