name: Master Branch Release Workflow

on:
    push:
        tags:
            - 'v*'

jobs:
    Build:
        uses: ./.github/workflows/build.yml
        secrets: inherit

    Draft-Release:
        needs: build-assets
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            # Create a draft release
            -   name: Create Draft Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref_name }}
                    release_name: TDM ${{ github.ref_name }}
                    draft: true

            -   name: Download artifacts from build
                uses: actions/download-artifact@v2
                with:
                    path: dist

            # Upload release assets: each file in `dist/` to the GitHub Release
            -   name: Upload Release Assets
                run: |
                    for asset in dist/tdmgr/*; do
                      echo "Uploading asset: $asset"
                      gh release upload "${{ github.ref_name }}" "$asset" --clobber
                    done
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
