name: Ruff

on:
    workflow_dispatch:
    pull_request:

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: chartboost/ruff-action@v1
                with:
                    version: 0.6.8
                    args: 'format --check'
