name: Build and upload to TestPyPI

on:
  push:
    branches:
      - cicd_update
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel setuptools_scm[toml] build
    
    - name: Build package
      run: python -m build --wheel --outdir dist/
    
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        repository_url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        packages_dir: dist
